apiVersion: v1
kind: Namespace
metadata:
  name:  python-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment
  namespace: python-ns
  labels:
    app: python
spec:
  #replicas: 1
  selector:
    matchLabels:
      app: python
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: ghcr.io/florina-alfred/proposal:c7e8456
        ports:
        - containerPort: 3000
          name: http-web-svc
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: python-service
  namespace: python-ns
  labels:
    app: python
    k8s-app: python
  annotations:
    alpha.monitoring.coreos.com/non-namespaced: "true"
spec:
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: python
  ports:
  - name: python-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
    #nodePort: 30100
---
#apiVersion: networking.k8s.io/v1
#kind: Ingress
#metadata:
#  name: python-ingress-external
#  namespace: python-ns
#spec:
#  rules:
#  - host: "py.redalf.de"
#    http:
#      paths:
#      - path: /
#        pathType: Prefix
#        backend:
#          service:
#            name: python-service
#            port:
#              number: 8080
#  tls:
#    - hosts:
#      - py.redalf.de
#      secretName: python-tls-secret
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: python-cert
#  namespace: python-ns
#spec:
#  secretName: python-tls-secret
#  issuerRef:
#    name: python-clusterissuer
#    kind: ClusterIssuer
#  dnsNames:
#    - py.home.local
#---
#apiVersion: autoscaling/v1
#kind: HorizontalPodAutoscaler
#metadata:
#  name: python-deployment
#  namespace: python-ns
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: python-deployment
#  minReplicas: 1
#  maxReplicas: 10
#  targetCPUUtilizationPercentage: 30
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: python-ingress-route
  namespace: python-ns
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`florina.redalf.test`) && PathPrefix(`/`) || Host(`florina.redalf.de`) && PathPrefix(`/`)  
      kind: Rule
      services:
        - name: python-service
          port: python-port
#      middlewares:
#        - name: cloudflarewarp
#          namespace: python-ns
#  tls:
#    secretName: python-tls-secret
#    domains:
#    - main: py.home.local
#      sans:
#        - py.redalf.de
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: python-http-cache
#spec:
#  plugin:
#    httpCache:
#      maxTtl: 30
#      memory:
#        limit: "10Mi"
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: python-add-trailing-slash
#  namespace: python-ns
#spec:
#  redirectRegex:
#    regex: ^.*/python$
#    replacement: /python/
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: python-stripprefix
#  namespace: python-ns
#spec:
#  stripPrefix:
#    prefixes:
#      - /python
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: Middleware
#metadata:
#  name: cloudflarewarp
#  namespace: python-ns
#spec:
#  plugin:
#    cloudflarewarp:
#      disableDefault: "false"
#---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-servicemonitor
  namespace: python-ns
  labels:
    k8s-app: python
    release: grafana-stack
spec:
  selector:
    matchLabels:
    - key: k8s-app
      #operator: Exists
  namespaceSelector:
    matchNames:
    - python-ns
  endpoints:
  - port: http-web-svc
    interval: 15s
    #path: /metrics
    #scheme: TCP
    #tlsConfig:
    #  insecureSkipVerify: true
---