apiVersion: apps/v1
kind: Deployment
metadata:
  name: komm-deployment
  labels:
    app: komm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komm
  template:
    metadata:
      labels:
        app: komm
    spec:
      containers:
      - name: komm-pro
        image: ghcr.io/florina-alfred/komm-pro:e1adefe
        volumeMounts:
          - name:  dev-video0
            mountPath: /dev/video0
        securityContext:
          privileged: true
        env:
        - name: BROKER_SERVER
          value: "kafka-0.kafka-headless.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "uuid_gen"
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "500m"
      - name: komm-con
        image: ghcr.io/florina-alfred/komm-con:e1adefe
        ports:
        - containerPort: 8000
          name: fastapi-port
        env:
        - name: BROKER_SERVER
          value: "kafka.default.svc.cluster.local"
        - name: KAFKA_TOPIC
          value: "uuid_gen"
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "500m"
      nodeSelector:
        kubernetes.io/hostname: server01
      volumes:
      - name: dev-video0
        hostPath:
          path:  /dev/video0
---
apiVersion: v1
kind: Service
metadata:
  name: komm-con-service
spec:
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: komm
  ports:
  - name: fastapi-svc-port
    protocol: TCP
    port: 8080
    targetPort: fastapi-port
    #nodePort: 30100
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: komm-con-ingress-route
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`komm.redalf.test`) && PathPrefix(`/`) || Host(`komm.redalf.de`) && PathPrefix(`/`)  
      kind: Rule
      services:
        - name: komm-con-service
          port: fastapi-svc-port
---
