apiVersion: apps/v1
kind: Deployment
metadata:
  name: komm-deployment
  labels:
    app: komm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komm
  template:
    metadata:
      labels:
        app: komm
    spec:
      containers:
      - name: komm-pro
        image: ghcr.io/florina-alfred/komm-pro:c76c912
        env:
        - name: BROKER_SERVER
          value: "kafka-0.kafka-headless.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "uuid_gen"
      - name: komm-con
        image: ghcr.io/florina-alfred/komm-con:c76c912
        env:
        - name: BROKER_SERVER
          value: "kafka.default.svc.cluster.local"
        - name: KAFKA_TOPIC
          value: "uuid_gen"
