apiVersion: apps/v1
kind: Deployment
metadata:
  name: komm-deployment
  labels:
    app: komm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komm
  template:
    metadata:
      labels:
        app: komm
    spec:
      containers:
      - name: komm-pro
        image: ghcr.io/florina-alfred/komm-pro:0c6fde1
      - name: komm-con
        image: ghcr.io/florina-alfred/komm-con:0c6fde1
