apiVersion: apps/v1
kind: Deployment
metadata:
  name: komm-pro-deployment
  namespace: default
  labels:
    app: komm-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komm-pro
  template:
    metadata:
      labels:
        app: komm-pro
    spec:
      containers:
      - name: komm-pro
        image: ghcr.io/florina-alfred/komm-pro:a0b15d3
        volumeMounts:
          - name:  dev-video0
            mountPath: /dev/video0
        securityContext:
          privileged: true
        env:
        - name: BROKER_SERVER
          value: "kafka-stack-0.kafka-stack-headless.default.svc.cluster.local:9092"
        - name: KAFKA_TOPIC
          value: "frame"
        - name: KAFKA_COMPRESSION
          value: "gzip"
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
      nodeSelector:
        kubernetes.io/hostname: server01
      volumes:
      - name: dev-video0
        hostPath:
          path:  /dev/video0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: komm-con-deployment
  namespace: default
  labels:
    app: komm-con
spec:
  replicas: 1
  selector:
    matchLabels:
      app: komm-con
  template:
    metadata:
      labels:
        app: komm-con
    spec:
      containers:
      - name: komm-con
        image: ghcr.io/florina-alfred/komm-con:a0b15d3
        ports:
        - containerPort: 8000
          name: fastapi-port
        env:
        - name: BROKER_SERVER
          value: "kafka-stack.default.svc.cluster.local"
        - name: KAFKA_TOPIC
          value: "frame"
        #command: [ "/bin/bash", "-c", "--" ]
        #args: [ "while true; do sleep 30; done;" ]
      nodeSelector:
        kubernetes.io/hostname: server01
      volumes:
      - name: dev-video0
        hostPath:
          path:  /dev/video0
---
apiVersion: v1
kind: Service
metadata:
  name: komm-con-service
  namespace: default
spec:
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: komm-con
  ports:
  - name: fastapi-svc-port
    protocol: TCP
    port: 8080
    targetPort: fastapi-port
    #nodePort: 30100
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: komm-con-ingress-route
  namespace: default
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: Host(`komm.redalf.test`) && PathPrefix(`/`) || Host(`komm.redalf.de`) && PathPrefix(`/`)  
      kind: Rule
      services:
        - name: komm-con-service
          port: fastapi-svc-port
---
