apiVersion: v1
kind: Namespace
metadata:
  name:  nginx-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-ns
  labels:
    app: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginxdemos/hello:latest
        ports:
        - containerPort: 80
          name: http-web-svc
        resources:
          requests:
            memory: "32Mi"
            cpu: "200m"
          limits:
            memory: "64Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-ns
spec:
  type: ClusterIP
  #type: NodePort
  #type: LoadBalancer
  selector:
    app: nginx
  ports:
  - name: nginx-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
    #nodePort: 30100
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: nginx-ingress-route
#  namespace: nginx-ns
#spec:
#  entryPoints:
#    - web
#    - websecure
#  routes:
#    - match: Host(`nginx.home.local`) && PathPrefix(`/`) || Host(`nginx.redalf.de`) && PathPrefix(`/`) 
#      kind: Rule
#      services:
#        - name: nginx-service
#          port: nginx-port
#  tls:
#    secretName: python-tls-secret
#    domains:
#    - main: nginx.home.local
#      sans:
#        - nginx.redalf.de
#---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  namespace: nginx-ns
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web, websecure
spec:
  rules:
  - host: "nginx.redalf.de"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 8080
#  tls:
#    - hosts:
#      - home.local
#      secretName: python-tls-secret
#---
#apiVersion: cert-manager.io/v1
#kind: Certificate
#metadata:
#  name: nginx-cert
#  namespace: nginx-ns
#spec:
#  secretName: python-tls-secret
#  issuerRef:
#    name: python-clusterissuer
#    kind: ClusterIssuer
#  dnsNames:
#    - home.local
---